// <auto-generated> by tools/extract_presets.py from reference/FissionOpt/web/overhaul.js. Do not edit. </auto-generated>

namespace FissionOpt.Core.Presets;

public static partial class OverhaulPresets
{
    /// <summary>One entry per addFuelPreset call: (fuel type OX/NI/ZA, fuel, efficiency %, heat, criticality, selfPriming).</summary>
    public static readonly OverhaulFuelPreset[] Fuels =
    {
        new("OX", "TBU", 125.0, 234, 40, false),
        new("OX", "LEU-233", 110.0, 78, 216, false),
        new("OX", "HEU-233", 115.0, 39, 648, false),
        new("OX", "LEU-235", 100.0, 102, 120, false),
        new("OX", "HEU-235", 105.0, 51, 360, false),
        new("OX", "LEN-236", 110.0, 70, 292, false),
        new("OX", "HEN-236", 115.0, 35, 876, false),
        new("OX", "LEP-239", 120.0, 99, 126, false),
        new("OX", "HEP-239", 125.0, 49, 378, false),
        new("OX", "LEP-241", 125.0, 84, 182, false),
        new("OX", "HEP-241", 130.0, 42, 546, false),
        new("OX", "MIX-239", 105.0, 94, 132, false),
        new("OX", "MIX-241", 115.0, 80, 192, false),
        new("OX", "LEA-242", 135.0, 65, 390, false),
        new("OX", "HEA-242", 140.0, 32, 1170, false),
        new("OX", "LECm-243", 145.0, 66, 384, false),
        new("OX", "HECm-243", 150.0, 33, 1152, false),
        new("OX", "LECm-245", 150.0, 75, 238, false),
        new("OX", "HECm-245", 155.0, 37, 714, false),
        new("OX", "LECm-247", 155.0, 72, 268, false),
        new("OX", "HECm-247", 160.0, 36, 804, false),
        new("OX", "LEB-248", 165.0, 73, 266, false),
        new("OX", "HEB-248", 170.0, 36, 798, false),
        new("OX", "LECf-249", 175.0, 60, 540, true),
        new("OX", "HECf-249", 180.0, 30, 1620, true),
        new("OX", "LECf-251", 180.0, 71, 288, true),
        new("OX", "HECf-251", 185.0, 35, 864, true),
        new("NI", "TBU", 125.0, 293, 32, false),
        new("NI", "LEU-233", 110.0, 98, 172, false),
        new("NI", "HEU-233", 115.0, 49, 516, false),
        new("NI", "LEU-235", 100.0, 128, 96, false),
        new("NI", "HEU-235", 105.0, 64, 288, false),
        new("NI", "LEN-236", 110.0, 88, 234, false),
        new("NI", "HEN-236", 115.0, 44, 702, false),
        new("NI", "LEP-239", 120.0, 124, 100, false),
        new("NI", "HEP-239", 125.0, 62, 300, false),
        new("NI", "LEP-241", 125.0, 105, 146, false),
        new("NI", "HEP-241", 130.0, 52, 438, false),
        new("NI", "MIX-239", 105.0, 118, 106, false),
        new("NI", "MIX-241", 115.0, 100, 154, false),
        new("NI", "LEA-242", 135.0, 81, 312, false),
        new("NI", "HEA-242", 140.0, 40, 936, false),
        new("NI", "LECm-243", 145.0, 83, 308, false),
        new("NI", "HECm-243", 150.0, 41, 924, false),
        new("NI", "LECm-245", 150.0, 94, 190, false),
        new("NI", "HECm-245", 155.0, 47, 570, false),
        new("NI", "LECm-247", 155.0, 90, 214, false),
        new("NI", "HECm-247", 160.0, 45, 642, false),
        new("NI", "LEB-248", 165.0, 91, 212, false),
        new("NI", "HEB-248", 170.0, 45, 636, false),
        new("NI", "LECf-249", 175.0, 75, 432, true),
        new("NI", "HECf-249", 180.0, 37, 1296, true),
        new("NI", "LECf-251", 180.0, 89, 230, true),
        new("NI", "HECf-251", 185.0, 44, 690, true),
        new("ZA", "TBU", 125.0, 199, 50, false),
        new("ZA", "LEU-233", 110.0, 66, 270, false),
        new("ZA", "HEU-233", 115.0, 33, 810, false),
        new("ZA", "LEU-235", 100.0, 87, 150, false),
        new("ZA", "HEU-235", 105.0, 43, 450, false),
        new("ZA", "LEN-236", 110.0, 60, 366, false),
        new("ZA", "HEN-236", 115.0, 30, 1098, false),
        new("ZA", "LEP-239", 120.0, 84, 158, false),
        new("ZA", "HEP-239", 125.0, 42, 474, false),
        new("ZA", "LEP-241", 125.0, 71, 228, false),
        new("ZA", "HEP-241", 130.0, 35, 684, false),
        new("ZA", "MIX-239", 105.0, 80, 166, false),
        new("ZA", "MIX-241", 115.0, 68, 240, false),
        new("ZA", "LEA-242", 135.0, 55, 488, false),
        new("ZA", "HEA-242", 140.0, 27, 1464, false),
        new("ZA", "LECm-243", 145.0, 56, 480, false),
        new("ZA", "HECm-243", 150.0, 28, 1440, false),
        new("ZA", "LECm-245", 150.0, 64, 298, false),
        new("ZA", "HECm-245", 155.0, 32, 894, false),
        new("ZA", "LECm-247", 155.0, 61, 336, false),
        new("ZA", "HECm-247", 160.0, 30, 1008, false),
        new("ZA", "LEB-248", 165.0, 62, 332, false),
        new("ZA", "HEB-248", 170.0, 31, 996, false),
        new("ZA", "LECf-249", 175.0, 51, 676, true),
        new("ZA", "HECf-249", 180.0, 25, 2028, true),
        new("ZA", "LECf-251", 180.0, 60, 360, true),
        new("ZA", "HECf-251", 185.0, 30, 1080, true),
    };

    /// <summary>Labels indexed by tile ID 0..40 (heat sinks, moderators, reflectors, shield, irradiator, conductor, air). Cells are named per fuel at run time.</summary>
    public static readonly string[] TileNames = { "Wt", "Fe", "Rs", "Qz", "Ob", "Nr", "Gs", "Lp", "Au", "Pm", "Sm", "En", "Pr", "Dm", "Em", "Cu", "Sn", "Pb", "B", "Li", "Mg", "Mn", "Al", "Ag", "Fl", "Vi", "Cb", "As", "N", "He", "Ed", "Cr", "##", "==", "--", "=)", "-)", "<>", "><", "[]", ".." };
    public static readonly string[] TileTitles = { "Water", "Iron", "Redstone", "Quartz", "Obsidian", "Nether Bricks", "Glowstone", "Lapis", "Gold", "Prismarine", "Slime", "End Stone", "Purpur", "Diamond", "Emerald", "Copper", "Tin", "Lead", "Boron", "Lithium", "Magnesium", "Manganese", "Aluminum", "Silver", "Fluorite", "Villiaumite", "Carobbiite", "Arsenic", "Nitrogen", "Helium", "Enderium", "Cryotheum", "Graphite", "Beryllium", "Heavy Water", "Beryllium-Carbon", "Lead-Steel", "Boron-Silver", "Irradiator", "Conductor", "Air" };
    /// <summary>Names used in the overhaul planner JSON (index 38, the irradiator, is itself a JSON object).</summary>
    public static readonly string[] TileSaveNames = { "Water", "Iron", "Redstone", "Quartz", "Obsidian", "NetherBrick", "Glowstone", "Lapis", "Gold", "Prismarine", "Slime", "EndStone", "Purpur", "Diamond", "Emerald", "Copper", "Tin", "Lead", "Boron", "Lithium", "Magnesium", "Manganese", "Aluminum", "Silver", "Fluorite", "Villiaumite", "Carobbiite", "Arsenic", "Nitrogen", "Helium", "Enderium", "Cryotheum", "Graphite", "Beryllium", "HeavyWater", "Beryllium-Carbon", "Lead-Steel", "Boron-Silver", "{\"HeatPerFlux\":0,\"EfficiencyMultiplier\":0.0}", "Conductor", "Air" };
    /// <summary>RGB text colors from web/overhaul.css, indexed by tile ID 0..40 (cells use the 'other' color).</summary>
    public static readonly int[] TileColors = { 0x1E90FF, 0xF5DEB3, 0xFF0000, 0xD3D3D3, 0x4B0082, 0x800000, 0xDDCC00, 0x0000FF, 0xFFD700, 0x66CDAA, 0x90EE90, 0xECF8B4, 0xBA55D3, 0xB0E0E6, 0x008000, 0xA52A2A, 0xB0C4DE, 0x2F4F4F, 0xC0C0C0, 0xE6E6FA, 0xFFC0CB, 0xAAAFCC, 0xD4F4E9, 0xFFE4E1, 0x8DAE99, 0x9A7161, 0x9EA654, 0x8F9284, 0x42A649, 0xF08080, 0x008080, 0x00BFFF, 0x000000, 0xCDD7BC, 0x6647D4, 0xC2996D, 0x90673B, 0x808080, 0x808080, 0x808080, 0xFFFFFF };
    public const int CellColor = 0x808080;
}
