#!/usr/bin/env python3
"""Mechanically extracts the preset tables from reference/FissionOpt/web/*.js into
C# source under src/ReactorOptimizer/FissionOpt.Core/Presets/. Re-run after
touching the upstream submodule; never hand-edit the generated files."""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
WEB = ROOT / "reference" / "FissionOpt" / "web"
OUT = ROOT / "src" / "ReactorOptimizer" / "FissionOpt.Core" / "Presets"

HEADER = "// <auto-generated> by tools/extract_presets.py from reference/FissionOpt/web/{src}. Do not edit. </auto-generated>\n"

def cs_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

def js_num(tok):
    # Keep the literal text so C# gets exactly what the JS had (e.g. 22.5, 1209.6).
    tok = tok.strip()
    float(tok)  # validate
    return tok if '.' in tok else tok + '.0'

def js_string_array(src, name):
    m = re.search(r"const %s = \[(.*?)\];" % re.escape(name), src, re.S)
    if not m:
        sys.exit("array %s not found" % name)
    return re.findall(r"'((?:[^'\\]|\\.)*)'", m.group(1))

# ---------------------------------------------------------------- classic
def classic():
    src = (WEB / "main.js").read_text()
    m = re.search(r"const fuelPresets = \{(.*?)\n  \};", src, re.S)
    if not m:
        sys.exit("fuelPresets not found")
    entries = re.findall(r"(\w+):\s*\[([\d.]+),\s*([\d.]+)\]", m.group(1))
    if not entries:
        sys.exit("no fuel presets parsed")

    def split(ident):
        for cfg in ("Def", "E2E", "PO3"):
            if ident.startswith(cfg):
                rest = ident[len(cfg):]
                break
        else:
            sys.exit("unknown config prefix in " + ident)
        cfg_name = {"Def": "Default", "E2E": "E2E", "PO3": "PO3"}[cfg]
        mm = re.fullmatch(r"([A-Za-z]+?)(\d+)(O?)", rest)
        mm2 = re.fullmatch(r"([A-Z]+?)(O?)", rest)  # TBU / TBUO: no isotope number
        if mm:
            fuel = "%s-%s" % (mm.group(1), mm.group(2))
            variant = "Oxide" if mm.group(3) else "Normal"
        elif mm2:
            fuel = mm2.group(1)
            variant = "Oxide" if mm2.group(2) else "Normal"
        else:
            fuel = re.sub(r"(?<=[a-z])(?=[A-Z])", " ", rest)  # UraniumIngot -> Uranium Ingot
            variant = ""
        return cfg_name, fuel, variant

    rate_presets = {}
    for cfg, pid in (("Default", "DefRate"), ("E2E", "E2ERate"), ("PO3", "PO3Rate")):
        mm = re.search(r"\$\('#%s'\)\.click\(\(\) => \{ loadRatePreset\(\[(.*?)\]\); \}\);" % pid, src, re.S)
        if not mm:
            sys.exit("rate preset %s not found" % pid)
        nums = [n.strip() for n in mm.group(1).replace("\n", " ").split(",")]
        if len(nums) != 30:
            sys.exit("rate preset %s has %d entries, expected 30" % (pid, len(nums)))
        rate_presets[cfg] = nums

    factors = {}
    for pid in ("br", "ic2", "ic2mox"):
        mm = re.search(r"\$\('#%s'\)\.click\(\(\) => \{ applyFuelFactor\((\d+) / (\d+)\); \}\);" % pid, src)
        if not mm:
            sys.exit("fuel factor %s not found" % pid)
        factors[pid] = (mm.group(1), mm.group(2))

    tile_names = js_string_array(src, "tileNames")
    tile_titles = js_string_array(src, "tileTitles")
    if len(tile_names) != 18 or len(tile_titles) != 18:
        sys.exit("expected 18 classic tile names/titles")
    # tileSaveNames = tileTitles.slice(0, 17) with three overrides (see main.js).
    save_names = tile_titles[:17]
    for mm in re.finditer(r"tileSaveNames\[(\d+)\] = '([^']*)';", src):
        save_names[int(mm.group(1))] = mm.group(2)

    out = [HEADER.format(src="main.js"), "namespace FissionOpt.Core.Presets;\n",
           "public static partial class ClassicPresets", "{"]
    out.append("    /// <summary>One entry per fuel button on leu-235.com: (config, fuel, variant, basePower, baseHeat).</summary>")
    out.append("    public static readonly ClassicFuelPreset[] Fuels =")
    out.append("    {")
    for ident, power, heat in entries:
        cfg, fuel, variant = split(ident)
        out.append("        new(%s, %s, %s, %s, %s, %s)," % (cs_str(cfg), cs_str(fuel), cs_str(variant), js_num(power), js_num(heat), cs_str(ident)))
    out.append("    };\n")
    out.append("    /// <summary>Cooling rates per cooler tile ID (0–14 passive, 15–29 active), keyed by modpack config.</summary>")
    out.append("    public static readonly CoolingRatePreset[] CoolingRates =")
    out.append("    {")
    for cfg, nums in rate_presets.items():
        out.append("        new(%s, new double[] { %s })," % (cs_str(cfg), ", ".join(js_num(n) for n in nums)))
    out.append("    };\n")
    out.append("    /// <summary>Multipliers applied to (power, heat) for third-party fuels; see the notes under the fuel table.</summary>")
    out.append("    public static readonly FuelFactor[] FuelFactors =")
    out.append("    {")
    labels = {"br": "ExtremeReactors Yellorium/Blutonium (use LEU-235)",
              "ic2": "IC2 Enriched Uranium (use LEU-235)",
              "ic2mox": "IC2 MOX (use MOX-239)"}
    for pid, (a, b) in factors.items():
        out.append("        new(%s, %s, %s.0 / %s.0)," % (cs_str(pid), cs_str(labels[pid]), a, b))
    out.append("    };\n")
    out.append("    /// <summary>Two-character labels indexed by cooler type 0–14, then Cell, Moderator, Air (18 entries).</summary>")
    out.append("    public static readonly string[] TileNames = { %s };" % ", ".join(cs_str(s) for s in tile_names))
    out.append("    public static readonly string[] TileTitles = { %s };" % ", ".join(cs_str(s) for s in tile_titles))
    out.append("    /// <summary>Block names used by Hellrage's Reactor Planner JSON (17 entries; Air is not saved).</summary>")
    out.append("    public static readonly string[] TileSaveNames = { %s };" % ", ".join(cs_str(s) for s in save_names))
    out.append("}")
    (OUT / "ClassicPresets.g.cs").write_text("\n".join(out) + "\n")
    print("classic: %d fuels, %d rate presets, %d factors" % (len(entries), len(rate_presets), len(factors)))

if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    classic()
